= pg-notes

== Setup
To get a already configured PostgreSQL version to play around with, a vagrant setup is used.
Just change into the project folder and run the Vagrant commands.

|===
|Command |Description

|vagrant up   | Initial start of Vagrant setup
|vagrant halt | Stop the Vagrant setup
|vagrant up   | Start of Vagrant setup again
|===


== Initial connection output
....
    default: Successfully created PostgreSQL dev virtual machine.
    default: Your PostgreSQL database has been setup and can be accessed on your local machine on the forwarded port (default: 15432)
    default:   Host: localhost
    default:   Port: 15432
    default:   Database: myapp
    default:   Username: myapp
    default:   Password: dbpass
    default: Admin access to postgres user via VM:
    default:   vagrant ssh
    default:   sudo su - postgres
    default:
    default: psql access to app database user via VM:
    default:   vagrant ssh
    default:   sudo su - postgres
    default:   PGUSER=myapp PGPASSWORD=dbpass psql -h localhost myapp
    default:
    default: Env variable for application development:
    default:   DATABASE_URL=postgresql://myapp:dbpass@localhost:15432/myapp
    default:
    default: Local command to access the database via psql:
    default:   PGUSER=myapp PGPASSWORD=dbpass psql -h localhost -p 15432 myapp
....

==